### ISSUE TITLE
Blurred BG disappears when app enter background

### ISSUE THREAD

**Issue by marcovanetti** [m1entus/MZFormSheetController#156]
1- A formsheet with native blurred BG is shown
2- The application enters background (e.g. home button pressed)
3- The application becomes active again
4- The native blurred background disappears

**Comment by cakl** [comment]
1+

**Comment by pipeaesac** [comment]
+1

**Comment by stefanomondino** [comment]
+1

**Comment by stefanomondino** [comment]
As temporary fix I was able to solve with these lines in my AppDelegate

- (void)applicationWillEnterForeground:(UIApplication *)application {
    if ([MZFormSheetController formSheetControllersStack].count>0){
        [[MZFormSheetController sharedBackgroundWindow] setHidden:YES];
        [MZFormSheetBackgroundWindow showBackgroundWindowAnimated:NO];
    }
}


Please note that showBackgroundWindowAnimated method is private, so you need make it public somewhere (I've put these lines in AppDelegate.m)

@interface MZFormSheetBackgroundWindow(Hack)
+(void) showBackgroundWindowAnimated:(BOOL)animated;
@end

**Comment by m1entus** [comment]
Fixed

**Comment by marcovanetti** [comment]
The issue is not resolved yet:

1- A formsheet with native blurred BG is shown
2- The application enters background (e.g. home button pressed)
3- The application becomes active again
4- The application enters background (e.g. home button pressed)
5- The application becomes active again
6- The native blurred background disappears

**Comment by m1entus** [comment]
Fixed
